name: "Automated License Compliance Checker"
description: "Scans projects for license compliance using Scancode Toolkit."

author: "Soheil Borhani <soheil.borhani@gmail.com>"
branding:
  color: "green"
  icon: "shield"

inputs:
  changed_files:
    description: "Path to a text file listing changed files to scan (one per line)."
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.allowed_licenses }}
    - ${{ inputs.changed_files }}
